# Cucumber Configuration Properties

# Plugin Configuration
plugin=pretty, html:reports/cucumber-report.html, json:reports/cucumber.json, junit:reports/cucumber.xml

# Feature File Location
features=src/test/resources/features

# Step Definition Location
glue=com.booking.stepDefinitions, com.booking.hooks

# Dry Run
dry.run=false

# Strict Mode
strict=true

# Default Language
default.language=en

# Publish Results
publish=true
publish.quiet=true